Repository paypal/Payouts-NodeJS-SDK, pull requests merged in 2021-02, with the labels that each got.

#9 fix variable name in Readme for get payout sample
  README.md
Labels: documentation

#4 chore: specify files to be included on install
  package.json
Labels: enhancement

#10 Release v1.1.0 - restrict files published to npm package, add samples for failure response handling
  CHANGELOG.md
  README.md
  lib/core/paypal_http_client.js
  package.json
  samples/cancelPayoutItem.js
  samples/createPayout.js
  samples/getPayout.js
  samples/getPayoutItem.js
  samples/package.json
  samples/runAll.js
  spec/payouts/payoutsPostTest.js
Labels: documentation, enhancement, release
